// popup.js — reads cookies for the active tab, builds a Netscape cookie file,
// and starts a download over a streaming port to the service worker. Also shows
// a progress bar and a recent-downloads list with open/reveal/drag actions.
// Per-download options (path, transcript, new folder) persist in storage.local.

const OPTION_DEFAULTS = {
  ytdlpPath: "yt-dlp.exe",
  outputDir: "%USERPROFILE%\\Downloads",
  template: '"{ytdlp}" -N 16 --recode-video mp4 --cookies "{cookies}" -P "{output}" -f "bv*+ba/b" "{url}"',
  premiereTemplate: "",
};

const STATE_DEFAULTS = {
  downloadPath: "",
  transcript: false,
  newFolder: false,
  premiere: false,
};

const $url = document.getElementById("url");
const $path = document.getElementById("path");
const $browse = document.getElementById("browse");
const $transcript = document.getElementById("transcript");
const $newFolder = document.getElementById("newFolder");
const $premiere = document.getElementById("premiere");
const $premiereLabel = document.getElementById("premiereLabel");
const $btn = document.getElementById("download");
const $status = document.getElementById("status");
const $inProgress = document.getElementById("inProgress");
const $inProgressList = document.getElementById("inProgressList");
const $recentList = document.getElementById("recentList");
const $clearRecent = document.getElementById("clearRecent");
$clearRecent.addEventListener("click", clearRecent);

function setStatus(text, cls) {
  $status.textContent = text;
  $status.className = cls || "";
}

function renderDoneOk(result) {
  $status.className = "ok";
  $status.textContent = "✓ Download finished. ";
  const a = document.createElement("a");
  a.textContent = "View in folder";
  a.className = "folder-link";
  a.addEventListener("click", () => {
    if (result.videoPath) chrome.runtime.sendMessage({ type: "reveal", path: result.videoPath });
    else if (result.folder) chrome.runtime.sendMessage({ type: "open", path: result.folder });
  });
  $status.appendChild(a);
}

// ---- In Progress (queue) ----
function renderQueue(list) {
  const jobs = list || [];
  $inProgress.hidden = jobs.length === 0;
  $inProgressList.textContent = "";
  for (const job of jobs) {
    const row = document.createElement("div");
    row.className = "job-item";

    const body = document.createElement("div");
    body.className = "jbody";

    const label = document.createElement("div");
    label.className = "jlabel";
    label.textContent = job.label || "";
    label.title = job.label || "";
    body.appendChild(label);

    if (job.status === "downloading") {
      const bar = document.createElement("div");
      bar.className = "bar";
      const fill = document.createElement("div");
      if (job.phase === "processing") fill.className = "processing";
      fill.style.width = Math.max(0, Math.min(100, job.percent || 0)) + "%";
      bar.appendChild(fill);
      body.appendChild(bar);

      const st = document.createElement("div");
      st.className = "jstatus";
      st.textContent = job.phase === "processing" ? "Processing…" : "Downloading " + (job.percent || 0) + "%";
      body.appendChild(st);
    } else {
      const st = document.createElement("div");
      st.className = "jstatus queued";
      st.textContent = "Queued";
      body.appendChild(st);
    }
    row.appendChild(body);

    const remove = document.createElement("span");
    remove.className = "remove";
    remove.textContent = "×";
    remove.title = job.status === "downloading" ? "Stop this download" : "Remove from queue";
    remove.addEventListener("click", () => port.postMessage({ cmd: "cancel", id: job.id }));
    row.appendChild(remove);

    $inProgressList.appendChild(row);
  }
}

// Convert a chrome.cookies.Cookie[] into Netscape cookies.txt text that yt-dlp reads.
function toNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# Generated by yt-dlp Downloader", ""];
  for (const c of cookies) {
    const includeSub = c.hostOnly ? "FALSE" : "TRUE";
    let domain = c.domain;
    if (!c.hostOnly && !domain.startsWith(".")) domain = "." + domain;
    const secure = c.secure ? "TRUE" : "FALSE";
    const expires = Math.round(c.expirationDate || 0);
    let line = [domain, includeSub, c.path, secure, expires, c.name, c.value].join("\t");
    if (c.httpOnly) line = "#HttpOnly_" + line;
    lines.push(line);
  }
  return lines.join("\n") + "\n";
}

async function getActiveTab() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab;
}
async function getOptions() {
  const stored = await chrome.storage.sync.get(OPTION_DEFAULTS);
  return { ...OPTION_DEFAULTS, ...stored };
}
function currentState() {
  return {
    downloadPath: $path.value.trim(),
    transcript: $transcript.checked,
    newFolder: $newFolder.checked,
    premiere: $premiere.checked,
  };
}
async function saveState() {
  await chrome.storage.local.set(currentState());
}

// ---- Recent list ----
const textCache = new Map(); // transcriptPath -> text (for drag)

function basename(p) {
  return (p || "").split(/[\\/]/).pop();
}
function stemOf(p) {
  return basename(p).replace(/\.[^.]+$/, "");
}

async function removeRecent(videoPath) {
  const { recent = [] } = await chrome.storage.local.get({ recent: [] });
  const next = recent.filter((r) => r.videoPath !== videoPath);
  await chrome.storage.local.set({ recent: next });
  renderRecent(next);
}

async function clearRecent() {
  await chrome.storage.local.set({ recent: [] });
  renderRecent([]);
}

function renderRecent(recent) {
  $recentList.textContent = "";
  $clearRecent.hidden = !(recent && recent.length);
  if (!recent || !recent.length) {
    const empty = document.createElement("div");
    empty.className = "recent-empty";
    empty.textContent = "No downloads yet.";
    $recentList.appendChild(empty);
    return;
  }
  for (const item of recent) {
    const row = document.createElement("div");
    row.className = "recent-item";

    const vIcon = document.createElement("span");
    vIcon.className = "icon";
    vIcon.textContent = "🎬";
    vIcon.title = "Open video";
    vIcon.addEventListener("click", () => chrome.runtime.sendMessage({ type: "open", path: item.videoPath }));
    row.appendChild(vIcon);

    if (item.transcriptPath) {
      const tIcon = document.createElement("span");
      tIcon.className = "icon";
      tIcon.textContent = "📄";
      tIcon.title = "Open captions (.srt) — drag into Premiere or Claude";
      tIcon.draggable = true;
      tIcon.addEventListener("click", () => chrome.runtime.sendMessage({ type: "open", path: item.transcriptPath }));
      tIcon.addEventListener("dragstart", (e) => {
        const text = textCache.get(item.transcriptPath) || "";
        const name = stemOf(item.transcriptPath) + ".srt";
        e.dataTransfer.setData("text/plain", text);
        const dataUri = "data:text/plain;charset=utf-8," + encodeURIComponent(text);
        e.dataTransfer.setData("DownloadURL", "application/x-subrip:" + name + ":" + dataUri);
      });
      row.appendChild(tIcon);
      // Prefetch the transcript text so dragstart can build the payload synchronously.
      if (!textCache.has(item.transcriptPath)) {
        chrome.runtime.sendMessage({ type: "readText", path: item.transcriptPath }, (resp) => {
          if (resp && resp.ok) textCache.set(item.transcriptPath, resp.text || "");
        });
      }
    }

    const name = document.createElement("span");
    name.className = "name";
    name.textContent = item.title || basename(item.videoPath);
    name.title = (item.title || "") + "\n" + (item.videoPath || "") + "\n(click to show in folder)";
    name.addEventListener("click", () => chrome.runtime.sendMessage({ type: "reveal", path: item.videoPath }));
    row.appendChild(name);

    const remove = document.createElement("span");
    remove.className = "remove";
    remove.textContent = "×";
    remove.title = "Remove from list";
    remove.addEventListener("click", (e) => {
      e.stopPropagation();
      removeRecent(item.videoPath);
    });
    row.appendChild(remove);

    $recentList.appendChild(row);
  }
}

// ---- Service worker port (progress + state) ----
const port = chrome.runtime.connect({ name: "ui" });
port.onMessage.addListener((msg) => {
  if (!msg) return;
  if (msg.ev === "state" || msg.ev === "queue") {
    renderQueue(msg.jobs);
  } else if (msg.ev === "recent") {
    renderRecent(msg.recent);
  } else if (msg.ev === "done") {
    const r = msg.result || {};
    if (r.ok && r.returncode === 0) {
      renderDoneOk(r);
    } else if (r.ok) {
      setStatus(`yt-dlp exited with code ${r.returncode}.\n` + (r.note || "") + "\n\n" + (r.stdout || "").slice(-1500), "err");
    } else {
      setStatus("Error: " + (r.error || "unknown"), "err");
    }
  }
});

let currentTab = null;

(async function init() {
  const state = await chrome.storage.local.get(STATE_DEFAULTS);
  const opts = await getOptions();
  $path.value = state.downloadPath || opts.outputDir;
  $transcript.checked = !!state.transcript;
  $newFolder.checked = !!state.newFolder;
  // The Premiere option only works when a template is configured in Settings.
  if (opts.premiereTemplate) {
    $premiere.checked = !!state.premiere;
  } else {
    $premiere.checked = false;
    $premiere.disabled = true;
    $premiereLabel.title = "Set a Premiere template in Settings to enable this.";
    $premiereLabel.style.opacity = "0.5";
  }

  const recent = (await chrome.storage.local.get({ recent: [] })).recent;
  renderRecent(recent);

  currentTab = await getActiveTab();
  if (!currentTab || !currentTab.url || !/^https?:/i.test(currentTab.url)) {
    $url.textContent = "No downloadable page in the active tab.";
    $btn.disabled = true;
    return;
  }
  $url.textContent = currentTab.url;
})();

// Checkbox coupling: enabling Transcript also enables New Folder (one-way).
$transcript.addEventListener("change", () => {
  if ($transcript.checked) $newFolder.checked = true;
  saveState();
});
$newFolder.addEventListener("change", saveState);
$path.addEventListener("change", saveState);

// Premiere project needs a per-video folder, so enabling it enables New Folder.
$premiere.addEventListener("change", () => {
  if ($premiere.checked) $newFolder.checked = true;
  saveState();
});

document.getElementById("opts").addEventListener("click", () => chrome.runtime.openOptionsPage());

$browse.addEventListener("click", async () => {
  $browse.disabled = true;
  const prev = $browse.textContent;
  $browse.textContent = "…";
  try {
    const resp = await chrome.runtime.sendMessage({ type: "pickFolder", current: $path.value.trim() });
    if (resp && resp.ok && resp.path) {
      $path.value = resp.path;
      await saveState();
    } else if (resp && !resp.ok) {
      setStatus("Folder picker unavailable: " + (resp.error || "unknown") + "\nType the path instead.", "err");
    }
  } catch (e) {
    setStatus("Browse error: " + (e && e.message ? e.message : String(e)), "err");
  } finally {
    $browse.disabled = false;
    $browse.textContent = prev;
  }
});

$btn.addEventListener("click", async () => {
  if (!currentTab) return;
  $btn.disabled = true; // briefly, to avoid double-firing while we gather cookies
  setStatus("Collecting cookies…", "run");
  try {
    await saveState();
    const cookies = await chrome.cookies.getAll({ url: currentTab.url });
    const cookiesText = toNetscape(cookies);
    const opts = await getOptions();
    const state = currentState();
    setStatus(`Queued (${cookies.length} cookies).`, "run");

    port.postMessage({
      cmd: "start",
      payload: {
        url: currentTab.url,
        label: currentTab.title || currentTab.url,
        cookiesText,
        template: opts.template,
        ytdlpPath: opts.ytdlpPath,
        outputDir: state.downloadPath || opts.outputDir,
        transcript: state.transcript,
        newFolder: state.newFolder,
        transcriptLang: "en",
        premiereProject: state.premiere,
        premiereTemplate: opts.premiereTemplate || "",
      },
    });
  } catch (e) {
    setStatus("Error: " + (e && e.message ? e.message : String(e)), "err");
  } finally {
    $btn.disabled = false;
  }
});
